apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: travel
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: abhishek661/travel-gateway:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: travel-config
                  key: APP_NAME
            - name: FLIGHTS_SVC
              valueFrom:
                configMapKeyRef:
                  name: travel-config
                  key: FLIGHTS_SVC
            - name: HOTELS_SVC
              valueFrom:
                configMapKeyRef:
                  name: travel-config
                  key: HOTELS_SVC
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: travel-secret
                  key: ADMIN_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
