apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights
  namespace: travel
  labels:
    app: flights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights
  template:
    metadata:
      labels:
        app: flights
    spec:
      containers:
        - name: flights
          image: abhishek661/travel-flights:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
        
