apiVersion: v1
kind: Service
metadata:
  name: flights
  namespace: travel
  labels:
    app: flights
spec:
  selector:
    app: flights
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
